import type { NextPage } from 'next';
import Head from 'next/head'
import { SearchContainer } from '../components/SearchContainer';
import { PopularMovies } from '../components/PopularMovies';

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SearchContainer />
        <PopularMovies />
      </main>
    </>
  )
}

export default Home;

