import type { NextPage } from 'next';
import Head from 'next/head'
// import { SearchBox } from '../components/SearchBox';
import { SearchContainer } from '../components/SearchContainer';
import styled from "@emotion/styled";


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SearchContainer />
      </main>
    </>
  )
}

export default Home;

